<script lang="ts">
  import type { GameSnapshot, Phase, PlayResult } from '../engine/contract';
  import CoinMeter from './CoinMeter.svelte'; import HandRack from './HandRack.svelte'; import EndTurnTransport from './EndTurnTransport.svelte'; import InterestGauge from './InterestGauge.svelte'; import LogPanel from './LogPanel.svelte'; import HintStrip from './HintStrip.svelte'; import DebugOverlay from './DebugOverlay.svelte'; import PilePanel from './PilePanel.svelte'; import HoverPanel from './HoverPanel.svelte'; import UnitStrip from './UnitStrip.svelte';
  import type { HoverContent } from './HoverPanel.svelte';
  type Pile = 'deck' | 'discard' | 'sell';
  type Props = { snapshot: GameSnapshot; hintVisible: boolean; debugVisible: boolean; hoverContent: HoverContent | null; dropResult?: PlayResult | null; onCanvasReady?: (el: HTMLDivElement) => void; onPick: (uid: string | null) => void; onSell: (uid: string) => void; onHover: (uid: string | null) => void; onEndTurn: () => void; onDismissHint: () => void; onRestart: () => void };
  let { snapshot, hintVisible, debugVisible, hoverContent, dropResult = null, onCanvasReady, onPick, onSell, onHover, onEndTurn, onDismissHint, onRestart }: Props = $props();
  let host = $state<HTMLDivElement | null>(null); let expanded = $state<Pile | null>(null);
  // Fire the canvas-host callback once the patch field mounts (one-shot bridge
  // creation lives in App; this avoids the $bindable/bind:this re-render loop)
  $effect(() => { if (host) onCanvasReady?.(host); });
  const isOver = $derived(snapshot.winner !== null);
  const winnerCopy = $derived(snapshot.winner === 'player' ? 'ACCOUNT SETTLED' : 'FORECLOSURE');
  const phaseEnabled = $derived(snapshot.phase === 'player' && !isOver);
</script>
<main class="desk-frame" aria-label="VU-Meter Desk battle console"><div class="desk-grain"></div><div class="frame-title"><span class="master-lamp" class:win={snapshot.winner === 'player'} class:loss={snapshot.winner === 'enemy'}></span><h1>GUPPY <em>THE DEBTOR</em></h1><p>DEBT DEPARTMENT / BATTLE CONSOLE</p></div><aside class="zone coin-zone"><CoinMeter coins={snapshot.coins} creditLimit={-5} /></aside><section class="patch-field" aria-label="Patch field reserved for battle canvas"><div class="field-label"><span>PATCH FIELD / 09 × 05</span><span>{snapshot.phase === 'player' ? 'OPERATOR LIVE' : 'AUTOMATED RESPONSE'}</span></div><div class="canvas-host" bind:this={host}><div class="canvas-placeholder"><span>PIXEL FIELD ROUTING PENDING</span><div class="patch-grid"></div></div></div><div class="unit-reference">{#each snapshot.units as unit (unit.uid)}<UnitStrip {unit} />{/each}</div></section><aside class="zone interest-zone"><InterestGauge turn={snapshot.turn} interestDue={snapshot.interestDue} winner={snapshot.winner} /></aside><aside class="zone log-zone"><LogPanel log={snapshot.log} /></aside><aside class="zone pile-zone"><PilePanel deckCount={snapshot.deck.length} discardCount={snapshot.discard.length} sellCount={snapshot.sellPile.length} deck={snapshot.deck} discard={snapshot.discard} sellPile={snapshot.sellPile} {expanded} onExpand={(pile) => expanded = pile} /></aside><aside class="zone hint-zone"><HintStrip visible={hintVisible} onDismiss={onDismissHint} /></aside><section class="hand-zone"><HandRack hand={snapshot.hand} coins={snapshot.coins} activeCardUid={snapshot.activeCardUid} {dropResult} {onPick} {onSell} {onHover} /></section><aside class="zone transport-zone"><EndTurnTransport phase={snapshot.phase as Phase} enabled={phaseEnabled} onPress={onEndTurn} /></aside><div class="hover-layer"><HoverPanel content={hoverContent} position="right" /></div><DebugOverlay snapshot={snapshot} visible={debugVisible} />{#if isOver}<section class="end-state" class:victory={snapshot.winner === 'player'}><div class="outcome-lamp"></div><h2>{winnerCopy}</h2><p>{snapshot.winner === 'player' ? 'MASTER CHANNEL CLEAR. GUARD THE LEDGER.' : 'DEBT PRESSURE EXCEEDED OPERATING LIMIT.'}</p><button onclick={onRestart}>RESTART BATTLE</button></section>{/if}</main>
<style>
  .desk-frame { position: fixed; inset: 0; overflow: hidden; isolation: isolate; background: radial-gradient(ellipse at 50% 38%, #74503a 0, var(--walnut) 39%, var(--walnut-deep) 100%); pointer-events: none; } .desk-frame::before { content: ''; position: absolute; z-index: -1; inset: 14px; border: 1px solid rgb(223 194 122 / .44); box-shadow: inset 0 0 0 7px rgb(15 10 7 / .34), inset 0 0 0 9px rgb(179 139 71 / .2), var(--shadow-inset); } .desk-frame::after { content: ''; position: absolute; z-index: 9; inset: 0; opacity: .12; pointer-events: none; background: repeating-linear-gradient(to bottom, transparent 0 3px, rgb(255 255 255 / .22) 4px 5px); animation: var(--scanline); } .desk-grain { position: absolute; inset: 0; z-index: -1; opacity: .25; background: repeating-radial-gradient(ellipse at 15% 30%, transparent 0 2px, rgb(0 0 0 / .28) 3px 4px, transparent 5px 9px); mix-blend-mode: multiply; }
  .frame-title { position: absolute; top: 31px; left: 50%; transform: translateX(-50%); display: grid; grid-template-columns: 11px auto; column-gap: 8px; color: var(--ivory-0); text-align: center; } .master-lamp { grid-row: span 2; align-self: center; width: 9px; height: 9px; border-radius: 50%; background: var(--amber); box-shadow: 0 0 8px var(--amber); animation: var(--lamp-flicker); } .master-lamp.win { background: var(--move); box-shadow: 0 0 9px var(--move); } .master-lamp.loss { background: var(--signal-red); box-shadow: 0 0 9px var(--signal-red); } h1 { font-family: var(--font-display); font-size: clamp(18px, 2.1vw, 29px); letter-spacing: .07em; } h1 em { color: var(--brass-light); font-style: normal; } .frame-title p { grid-column: 2; margin-top: 3px; color: var(--ivory-2); font-size: 8px; letter-spacing: .16em; }
  .zone { position: absolute; } .coin-zone { left: 34px; top: 16vh; } .interest-zone { top: 31px; right: 39px; } .log-zone { left: 150px; top: 108px; } .pile-zone { left: 150px; bottom: 199px; position: absolute; } .hint-zone { left: 50%; bottom: 208px; transform: translateX(-50%); } .transport-zone { right: 37px; bottom: 35px; } .hand-zone { position: absolute; left: 50%; bottom: 25px; transform: translateX(-50%); }
  .patch-field { position: absolute; left: 50%; top: 50%; width: min(59vw, 840px); height: min(52vh, 490px); transform: translate(-50%, -44%); padding: 25px 29px 22px; border: 8px solid #302c25; border-radius: 5px; background: linear-gradient(145deg, #73756d, #3e403b); box-shadow: 0 16px 30px rgb(0 0 0 / .4), inset 0 0 0 2px #a9a99c, inset 0 0 0 7px #21231e; } .field-label { position: absolute; top: 7px; left: 12px; right: 12px; display: flex; justify-content: space-between; color: var(--ivory-0); font-size: 8px; letter-spacing: .13em; } .field-label span:last-child { color: var(--brass-light); } .canvas-host { width: 100%; height: 100%; border: 1px solid var(--ink); background: var(--ivory-1); pointer-events: none; overflow: hidden; } .canvas-placeholder { position: relative; display: grid; place-items: center; width: 100%; height: 100%; color: var(--ink-soft); font-size: 9px; letter-spacing: .12em; } .patch-grid { position: absolute; inset: 9%; opacity: .45; background: linear-gradient(90deg, transparent 10.6%, var(--ink-soft) 10.8% 11%, transparent 11.2%), linear-gradient(transparent 19%, var(--ink-soft) 19.3% 19.5%, transparent 19.7%); background-size: 11.11% 100%, 100% 20%; border: 1px solid var(--ink-soft); } .unit-reference { position: absolute; display: flex; flex-wrap: wrap; gap: 6px; right: 18px; top: 35px; width: 142px; }
  .hover-layer { position: absolute; right: calc(20vw - 30px); top: 54%; z-index: 8; } .end-state { position: absolute; z-index: 15; left: 50%; top: 50%; width: 380px; transform: translate(-50%, -50%); padding: 31px; border: 1px solid var(--steel-light); background: rgb(29 18 13 / .95); color: var(--ivory-0); text-align: center; pointer-events: auto; box-shadow: var(--shadow-lift); } .outcome-lamp { width: 15px; height: 15px; margin: 0 auto 14px; border-radius: 50%; background: var(--signal-red); box-shadow: 0 0 15px var(--signal-red); } .victory .outcome-lamp { background: var(--move); box-shadow: 0 0 15px var(--move); } .end-state h2 { font-family: var(--font-display); letter-spacing: .08em; } .end-state p { margin: 10px auto 19px; color: var(--ivory-2); font-size: 10px; line-height: 1.45; } .end-state button { padding: 9px 12px; border: 1px solid var(--brass); background: var(--brass); color: var(--ink); cursor: pointer; font-size: 10px; font-weight: 700; letter-spacing: .07em; }
  @media (max-width: 1050px) { .log-zone { left: 120px; } .patch-field { width: 61vw; } .unit-reference { display: none; } .hand-zone { transform: translateX(-50%) scale(.88); transform-origin: bottom center; } }
</style>
