<script lang="ts">
  import type { Card } from '../engine/contract';
  type Pile = 'deck' | 'discard' | 'sell';
  type Props = { deckCount: number; discardCount: number; sellCount: number; deck: Card[]; discard: Card[]; sellPile: Card[]; expanded: Pile | null; onExpand: (pile: Pile | null) => void };
  let { deckCount, discardCount, sellCount, deck, discard, sellPile, expanded, onExpand }: Props = $props();
  const activeCards = $derived(expanded === 'deck' ? deck : expanded === 'discard' ? discard : sellPile);
</script>
<section class="piles" aria-label="Card piles"><div class="pile-row"><button onclick={() => onExpand(expanded === 'deck' ? null : 'deck')}><span class="back-stack"></span><b>DECK</b><strong>{deckCount}</strong></button><button onclick={() => onExpand(expanded === 'discard' ? null : 'discard')}><span class="discard-face">{discard.at(-1)?.name?.slice(0, 1) ?? '—'}</span><b>DISC</b><strong>{discardCount}</strong></button><button onclick={() => onExpand(expanded === 'sell' ? null : 'sell')}><span class="sell-stack"></span><b>SELL</b><strong>{sellCount}</strong></button></div>{#if expanded}<div class="pile-list"><header><span>{expanded.toUpperCase()} REGISTER</span><button onclick={() => onExpand(null)}>CLOSE</button></header>{#if activeCards.length}{#each activeCards as card (card.uid)}<p><i class={card.pitch}></i>{card.name}<span>{card.cost}c / +{card.coinValue}</span></p>{/each}{:else}<p class="none">No cards registered.</p>{/if}</div>{/if}</section>
<style>.piles { pointer-events: auto; color: var(--ivory-1); } .pile-row { display: flex; gap: 7px; } .pile-row button { display: grid; grid-template-columns: 24px auto; grid-template-rows: auto auto; gap: 0 5px; min-width: 66px; padding: 5px; border: 1px solid var(--steel); background: var(--walnut-deep); color: inherit; cursor: pointer; text-align: left; } .pile-row button:hover { border-color: var(--brass); } .back-stack, .sell-stack, .discard-face { grid-row: span 2; width: 20px; height: 27px; border: 1px solid var(--steel-light); background: repeating-linear-gradient(45deg, var(--steel) 0 2px, var(--walnut-deep) 2px 4px); } .sell-stack { background: var(--brass); } .discard-face { display: grid; place-items: center; background: var(--ivory-1); color: var(--ink); font-weight: 800; } b { font-size: 8px; letter-spacing: .1em; } strong { color: var(--brass-light); font-size: 13px; letter-spacing: -.08em; } .pile-list { position: absolute; z-index: 10; bottom: calc(100% + 8px); width: 245px; max-height: 220px; overflow: auto; padding: 9px; border: 1px solid var(--steel-light); background: var(--walnut-deep); box-shadow: var(--shadow-lift); } .pile-list header { display: flex; justify-content: space-between; padding-bottom: 6px; border-bottom: 1px solid var(--steel); color: var(--brass-light); font-size: 8px; letter-spacing: .1em; } .pile-list button { border: 0; background: transparent; color: var(--ivory-1); cursor: pointer; font-size: 8px; } .pile-list p { display: flex; gap: 6px; align-items: center; padding: 5px 0; border-bottom: 1px solid rgb(168 170 160 / .2); font-size: 9px; } .pile-list p span { margin-left: auto; color: var(--ivory-2); } .pile-list i { width: 6px; height: 6px; border-radius: 50%; } i.red { background: var(--signal-red); } i.yellow { background: var(--amber); } i.blue { background: var(--move); } .none { color: var(--ivory-2); }</style>
